name: thesis
channels:
  - conda-forge
  - pytorch
  - nvidia
  - dglteam/label/cu117
dependencies:
  - python=3.10
  - pip
  - imageio
  - numpy=1.24
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - pillow
  - wandb
  - simplejson
  - pytorch=1.13.0
  - torchvision
  - pytorch-cuda=11.7
  - dgl
  - yapf
  - pip:
    - -r requirements.txt
