name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy 
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - pillow
  - wandb
  - simplejson
  - pip:
    - -r requirements.txt