# pytorch_lightning==1.8.1
fit:
  seed_everything: 43
  trainer:
    logger: WandbLogger
    enable_checkpointing: true
    callbacks: null
    default_root_dir: "/nfs/home/rhotertj/Code/thesis/experiments/mvit"
    gradient_clip_val: null
    gradient_clip_algorithm: null
    num_nodes: 1
    num_processes: null
    devices: 1
    gpus: null
    auto_select_gpus: false
    tpu_cores: null
    ipus: null
    enable_progress_bar: true
    overfit_batches: false
    track_grad_norm: -1
    check_val_every_n_epoch: 5
    fast_dev_run: false
    accumulate_grad_batches: 16
    max_epochs: 50
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    limit_train_batches: 0.1
    limit_val_batches: 0.1
    limit_test_batches: null
    limit_predict_batches: null
    val_check_interval: null
    log_every_n_steps: 50
    accelerator: "gpu"
    strategy: null
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    num_sanity_val_steps: 1
    resume_from_checkpoint: null
    profiler: null
    benchmark: null
    deterministic: null
    reload_dataloaders_every_n_epochs: 0
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: true
    plugins: null
    amp_backend: native
    amp_level: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    inference_mode: true
  model:
    pretrained_path: "models/mvit_b_16x4.pt"
    learning_rate: 0.01
    num_classes: 3
  data:
    meta_path: "/nfs/home/rhotertj/datasets/hbl/meta3d.csv"
    seq_len: 16
    sampling_rate: 4
    load_frames: true
    batch_size: 2
  ckpt_path: null
