seed_everything: 43
stage: train
logger:
  project: thesis_mvit
  offline: false
trainer: # logger extra
  devices: 1
  overfit_batches: False # change int of n batches to debug with n batches
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 2
  max_epochs: 50
  max_steps: -1
  max_time: null
  limit_train_batches: 0.01 # set fraction of training data
  limit_val_batches: 0.1
  limit_test_batches: null
  log_every_n_steps: 50
  accelerator: "gpu"
  precision: 32
  num_sanity_val_steps: 1
dataset: LitMultiModalHblDataset
data:
  meta_path_train: "/nfs/home/rhotertj/datasets/hbl/meta3d_train.csv"
  meta_path_val: "/nfs/home/rhotertj/datasets/hbl/meta3d_val.csv"
  meta_path_test: "/nfs/home/rhotertj/datasets/hbl/meta3d_test.csv"
  seq_len: 16
  sampling_rate: 2
  load_frames: true
  batch_size: 16
  overlap: false
model_class: LitMViT
model:
  pretrained_path: "models/mvit_b_16x4.pt"
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 1e-4
num_classes: 3
checkpoint: ""
callbacks:
  checkpointing:
    every_n: 1
    dir: experiments/mvit/debug
save_config: true