seed_everything: 43
stage: train
logger:
  project: thesis_mvit
  name: debug
  offline: false
trainer: # logger extra
  default_root_dir: "/experiments/mvit/debug"
  num_nodes: 1
  devices: 1
  overfit_batches: 20 # change int of n batches to debug with n batches
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 16
  max_epochs: 5
  max_steps: -1
  max_time: null
  limit_train_batches: 0.01 # set fraction of training data
  limit_val_batches: 0.1
  limit_test_batches: null
  log_every_n_steps: 50
  accelerator: "gpu"
  precision: 32
  num_sanity_val_steps: 1
data:
  meta_path: "/nfs/home/rhotertj/datasets/hbl/meta3d.csv"
  seq_len: 16
  sampling_rate: 4
  load_frames: true
  batch_size: 2
model:
  pretrained_path: "models/mvit_b_16x4.pt"
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 1e-4
  num_classes: 3
checkpoint: ""