seed_everything: 43
stage: train
logger:
  project: thesis_mvit

trainer: # logger extra
  num_nodes: 1
  devices: 1
  overfit_batches: false # change int of n batches to debug with n batches
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 4
  max_epochs: 30
  max_steps: -1
  max_time: null
  limit_train_batches: null # set fraction of training data
  limit_val_batches: null
  limit_test_batches: null
  log_every_n_steps: 50
  accelerator: "gpu"
  precision: 32
  num_sanity_val_steps: 1

data:
  name: LitResampledHblDataset
  params:
    meta_path: "/nfs/home/rhotertj/datasets/hbl/meta3d.csv"
    idx_mapping_train: "/nfs/home/rhotertj/datasets/hbl/resampled/balanced/True/overlap/True/sql_sr/16x2/mode/time/meta3d_train.jsonl"
    idx_mapping_val: "/nfs/home/rhotertj/datasets/hbl/resampled/balanced/True/overlap/True/sql_sr/16x2/mode/time/meta3d_val.jsonl"
    idx_mapping_test: "/nfs/home/rhotertj/datasets/hbl/resampled/balanced/True/overlap/True/sql_sr/16x2/mode/time/meta3d_test.jsonl"
    seq_len: 16
    sampling_rate: 2
    load_frames: true
    batch_size: 8
    epsilon : 7
    mix_video: True
  transforms: 
    - name: vt.FrameSequenceToTensor
    - name: vt.RandomHorizontalFlipVideo
      params:
        p: 0.5
    - name: vt.TimeFirst
    - name: t.ColorJitter
      params:
        brightness: 0.2
        hue: 0.2
        contrast: 0.2
        saturation: 0.2
    # - name: ptvt.RandAugment
    #   params:
    #     num_layers: 3
    #     prob: 0.5
    #     magnitude: 5
    - name: vt.ChannelFirst
    - name: t.Resize
      params:
        size: [224, 224]

model:
  name: make_kinetics_mvit
  params:
    pretrained_path: "models/mvit_b_16x4.pt"

lit_model:
  name: LitUniModal
  params:
    momentum: 0.9
    learning_rate: 0.03
    weight_decay: 1e-4
    loss_func: unweighted_cross_entropy

num_classes: 3
checkpoint: null
save_config: true
log_proportions: true

callbacks:
  checkpointing:
    every_n: 1
    dir: experiments/mvit/train
  early_stopping:
    monitor: "train/acc"
    patience: 3
    mode: max
    check_on_train_epoch_end: True