# pytorch_lightning==1.8.1
seed_everything: 42
trainer:
  logger: WandbLogger
  enable_checkpointing: true
  callbacks: null
  default_root_dir: checkpoints/timesformer/classification
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: 1
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 5
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 200
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: "gpu"
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: true
  replace_sampler_ddp: true
  detect_anomaly: true
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
model:
  seq_len: 8
  n_players: 22
  n_player_labels: 300
  n_ball_labels: 1000
  nhead: 8
  embed_dim: 512
  attention_type: divided_space_time
  learning_rate: 0.1
  task: classification
  head: custom
data:
  binned: true
  bins_width: 20
  bins_length: 50
  batch_size: 8
  normalize: true
  seq_len: 8
ckpt_path: null
